# GitLab CI configuration file
# see documentation on https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
    - build
    - test
    - push

pedef:build:
    stage: build
    image: dockette/docker
    tags:
        - docker
    only:
        - master
    script:
        - docker build -t docker.nexus.ispa.cz/ispa/pedef:$CI_COMMIT_REF_SLUG .

pedef:test:
    stage: test
    image: dockette/docker
    tags:
        - docker
    only:
        - master
    script:
        - docker run docker.nexus.ispa.cz/ispa/pedef:$CI_COMMIT_REF_SLUG bash -c "rm -rf node_modules && npm install && npm run fulltest"

pedef:publish:
    stage: push
    image: dockette/docker
    tags:
        - docker
    only:
        - master
    before_script:
        - docker login -u ${NEXUS_DOCKER_ISPA_USER} -p ${NEXUS_DOCKER_ISPA_PASSWORD} ${NEXUS_DOCKER_URL}
    script:
        - docker push docker.nexus.ispa.cz/ispa/pedef:$CI_COMMIT_REF_SLUG
